import { BankAccount, Category, CostCenter, PayableItem, ReceivableItem, Supplier } from '@/types';

// Requirement: Start with 0 pre-defined banks by default so user can create their own banks
export const initialBankAccounts: BankAccount[] = [];

export const initialCostCenters: CostCenter[] = [
  { id: 'cc-1', code: 'CC-01', name: 'Torre Forte Church', description: 'Centro de Custo Geral / Sede da Igreja', isActive: true, createdAt: '2026-01-01T00:00:00.000Z' },
  { id: 'cc-2', code: 'CC-02', name: 'Homens', description: 'Ministério e Eventos de Homens', isActive: true, createdAt: '2026-01-01T00:00:00.000Z' },
  { id: 'cc-3', code: 'CC-03', name: 'Mulheres', description: 'Ministério e Eventos de Mulheres', isActive: true, createdAt: '2026-01-01T00:00:00.000Z' },
  { id: 'cc-4', code: 'CC-04', name: 'Kids', description: 'Ministério Infantil Torre Kids', isActive: true, createdAt: '2026-01-01T00:00:00.000Z' },
];

export const initialCategories: Category[] = [
  // ENTRADAS
  { id: 'cat-1', code: '1.1.01', name: 'Dízimos', type: 'ENTRADA', description: 'Contribuição regular dos membros', isActive: true },
  { id: 'cat-2', code: '1.1.02', name: 'Ofertas dos Cultos', type: 'ENTRADA', description: 'Ofertas voluntárias arrecadadas nas reuniões', isActive: true },
  { id: 'cat-3', code: '1.1.03', name: 'Ofertas de Missões', type: 'ENTRADA', description: 'Ofertas direcionadas para sustento missionário', isActive: true },
  { id: 'cat-4', code: '1.1.04', name: 'Doações Especiais', type: 'ENTRADA', description: 'Doações direcionadas para obras e reformas', isActive: true },
  { id: 'cat-5', code: '1.2.01', name: 'Eventos e Cantinas', type: 'ENTRADA', description: 'Arrecadação com congressos e eventos sociais', isActive: true },

  // SAÍDAS
  { id: 'cat-6', code: '2.1.01', name: 'Energia Elétrica', type: 'SAIDA', description: 'Conta de luz da igreja e dependências', isActive: true },
  { id: 'cat-7', code: '2.1.02', name: 'Água e Esgoto', type: 'SAIDA', description: 'Conta de água e esgoto', isActive: true },
  { id: 'cat-8', code: '2.1.03', name: 'Aluguel do Templo', type: 'SAIDA', description: 'Locação do espaço de culto principal', isActive: true },
  { id: 'cat-9', code: '2.2.01', name: 'Prebenda Pastoral / Salários', type: 'SAIDA', description: 'Sustento pastoral e encargo ministerial', isActive: true },
  { id: 'cat-10', code: '2.3.01', name: 'Manutenção e Conservação', type: 'SAIDA', description: 'Reparos no prédio, pintura e zeladoria', isActive: true },
  { id: 'cat-11', code: '2.3.02', name: 'Equipamentos de Som e Vídeo', type: 'SAIDA', description: 'Compra e conserto de equipamentos de mídia', isActive: true },
  { id: 'cat-12', code: '2.4.01', name: 'Material EBD e Discipulado', type: 'SAIDA', description: 'Revistas da escola dominical e apostilas', isActive: true },
  { id: 'cat-13', code: '2.5.01', name: 'Ação Social e Cestas Básicas', type: 'SAIDA', description: 'Auxílio a famílias carentes da comunidade', isActive: true },
];

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup-1',
    name: 'Companhia de Energia Elétrica S.A.',
    personType: 'PJ',
    cnpj: '12345678000190',
    phone: '08007272000',
    email: 'atendimento@energiaeletrica.com.br',
    createdAt: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'sup-2',
    name: 'Saneamento Básico & Água S.A.',
    personType: 'PJ',
    cnpj: '98765432000110',
    phone: '08000110195',
    email: 'faturamento@saneamento.com.br',
    createdAt: '2026-01-10T10:30:00.000Z',
  },
  {
    id: 'sup-3',
    name: 'Imobiliária Central da Cidade Ltda',
    personType: 'PJ',
    cnpj: '11222333000144',
    phone: '1133334444',
    email: 'alugueis@imobiliariacentral.com.br',
    createdAt: '2026-01-15T14:00:00.000Z',
  },
  {
    id: 'sup-4',
    name: 'Editora de Literatura Cristã Ltda',
    personType: 'PJ',
    cnpj: '55444333000122',
    phone: '1140045555',
    email: 'vendas@editoracrista.com.br',
    createdAt: '2026-02-01T09:15:00.000Z',
  },
  {
    id: 'sup-5',
    name: 'João Pedro da Silva - Som & Iluminação',
    personType: 'PF',
    cpf: '12345678900',
    phone: '11988887777',
    email: 'joao.som@gmail.com',
    createdAt: '2026-02-10T11:20:00.000Z',
  },
  {
    id: 'sup-6',
    name: 'Supermercado Bom Preço Ltda',
    personType: 'PJ',
    cnpj: '77888999000155',
    phone: '11977776666',
    email: 'contato@bompreco.com.br',
    createdAt: '2026-02-18T16:45:00.000Z',
  }
];

export const initialPayables: PayableItem[] = [
  {
    id: 'pay-1',
    categoryId: 'cat-6',
    categoryName: 'Energia Elétrica',
    costCenterId: 'cc-1',
    costCenterName: 'Torre Forte Church',
    supplierId: 'sup-1',
    supplierName: 'Companhia de Energia Elétrica S.A.',
    supplierCpfCnpj: '12.345.678/0001-90',
    value: 1250.80,
    invoiceValue: 1250.80,
    observation: 'Conta de luz referente ao mês corrente do templo principal.',
    invoiceNumber: 'NF-892110',
    dueDate: '2026-10-15',
    status: 'PENDENTE',
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'pay-2',
    categoryId: 'cat-8',
    categoryName: 'Aluguel do Templo',
    costCenterId: 'cc-1',
    costCenterName: 'Torre Forte Church',
    supplierId: 'sup-3',
    supplierName: 'Imobiliária Central da Cidade Ltda',
    supplierCpfCnpj: '11.222.333/0001-44',
    value: 4500.00,
    invoiceValue: 4500.00,
    observation: 'Aluguel mensal do templo e estacionamento anexo.',
    invoiceNumber: 'REC-2026-09',
    dueDate: '2026-10-10',
    status: 'PENDENTE',
    createdAt: '2026-09-01T09:00:00.000Z',
  },
  {
    id: 'pay-3',
    categoryId: 'cat-7',
    categoryName: 'Água e Esgoto',
    costCenterId: 'cc-1',
    costCenterName: 'Torre Forte Church',
    supplierId: 'sup-2',
    supplierName: 'Saneamento Básico & Água S.A.',
    supplierCpfCnpj: '98.765.432/0001-10',
    value: 480.30,
    invoiceValue: 480.30,
    observation: 'Consumo de água dos banheiros e cozinha.',
    invoiceNumber: 'FAT-44512',
    dueDate: '2026-10-28',
    status: 'PENDENTE',
    createdAt: '2026-09-02T10:00:00.000Z',
  },
  {
    id: 'pay-4',
    categoryId: 'cat-12',
    categoryName: 'Material EBD e Discipulado',
    costCenterId: 'cc-4',
    costCenterName: 'Kids',
    supplierId: 'sup-4',
    supplierName: 'Editora de Literatura Cristã Ltda',
    supplierCpfCnpj: '55.444.333/0001-22',
    value: 430.00,
    invoiceValue: 860.00,
    observation: 'Revistas da Escola Dominical Infantil (Parcela 1 de 2)',
    invoiceNumber: 'NF-10492',
    dueDate: '2026-10-25',
    installmentInfo: { current: 1, total: 2, groupId: 'group-ebd-1' },
    status: 'PENDENTE',
    createdAt: '2026-09-05T14:30:00.000Z',
  },
  {
    id: 'pay-5',
    categoryId: 'cat-12',
    categoryName: 'Material EBD e Discipulado',
    costCenterId: 'cc-4',
    costCenterName: 'Kids',
    supplierId: 'sup-4',
    supplierName: 'Editora de Literatura Cristã Ltda',
    supplierCpfCnpj: '55.444.333/0001-22',
    value: 430.00,
    invoiceValue: 860.00,
    observation: 'Revistas da Escola Dominical Infantil (Parcela 2 de 2)',
    invoiceNumber: 'NF-10492',
    dueDate: '2026-11-25',
    installmentInfo: { current: 2, total: 2, groupId: 'group-ebd-1' },
    status: 'PENDENTE',
    createdAt: '2026-09-05T14:30:00.000Z',
  }
];

export const initialReceivables: ReceivableItem[] = [
  {
    id: 'rec-1',
    categoryId: 'cat-1',
    categoryName: 'Dízimos',
    costCenterId: 'cc-1',
    costCenterName: 'Torre Forte Church',
    supplierName: 'Membros da Igreja',
    value: 8450.00,
    observation: 'Entradas de dízimos arrecadados no 1º domingo do mês.',
    dueDate: '2026-10-06',
    status: 'PENDENTE',
    createdAt: '2026-09-06T20:00:00.000Z',
  },
  {
    id: 'rec-2',
    categoryId: 'cat-2',
    categoryName: 'Ofertas dos Cultos',
    costCenterId: 'cc-1',
    costCenterName: 'Torre Forte Church',
    supplierName: 'Culto de Domingo (Noite)',
    value: 1820.50,
    observation: 'Oferta arrecadada no culto de celebração.',
    dueDate: '2026-10-06',
    status: 'PENDENTE',
    createdAt: '2026-09-06T21:30:00.000Z',
  },
  {
    id: 'rec-3',
    categoryId: 'cat-5',
    categoryName: 'Eventos e Cantinas',
    costCenterId: 'cc-2',
    costCenterName: 'Homens',
    supplierName: 'Ministério de Homens',
    value: 560.00,
    observation: 'Ingressos Encontro de Homens (Parcela 1 de 2)',
    dueDate: '2026-10-25',
    installmentInfo: { current: 1, total: 2, groupId: 'rec-grp-1' },
    status: 'PENDENTE',
    createdAt: '2026-09-20T10:00:00.000Z',
  }
];
